version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ms-backend
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - LOCAL_MODEL_PATH=/app/backend/models/spectrum_predictor.pkl
      - FLASK_ENV=production
      # ADD CORS ENVIRONMENT VARIABLES
      - CORS_ORIGINS=http://localhost:3001,http://frontend
    volumes:
      - ./backend/models:/app/backend/models
    ports:
      - "5050:5050"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    container_name: ms-frontend
    depends_on:
      - backend
    environment:
      - NGINX_PORT=80
    ports:
      - "3001:80"
    restart: unless-stopped

networks:
  default:
    name: ms-net 