"""File format utilities."""
from typing import Dict, Tuple
from .chemistry import safe_filename

def peaks_to_msp(pred: Dict, scale_to: float = 1000.) -> Tuple[str, str]:
    """
    Build an MSP block from one prediction record.
    Returns (msp_text, filename_without_extension)
    """
    peaks = pred["peaks"]
    if not peaks:
        # build empty shell – rare, but keeps the API consistent
        peaks_block = "Num Peaks: 0\n"
    else:
        max_i = max(p["intensity"] for p in peaks) or 1.0
        factor = scale_to / max_i                # ints are already 0-1
        peaks_block = f"Num Peaks: {len(peaks)}\n"
        for p in peaks:
            mz = f"{p['mz']:.6f}"
            inten = f"{p['intensity'] * factor:.1f}"
            peaks_block += f"{mz}\t{inten}\n"

    header = [
        f"NAME: {pred['smiles']}",
        "PRECURSORMZ: ",
        "PRECURSORTYPE: ",
        f"FORMULA: ",
        "Ontology: ",
        "INCHIKEY: ",
        "INCHI: ",
        f"SMILES: {pred['smiles']}",
        "RETENTIONTIME: ",
        "CCS: ",
        "IONMODE: Positive",
        "INSTRUMENTTYPE: LC-ESI-qTof",
        "INSTRUMENT: simulation",
        "COLLISIONENERGY: ",
        "Comment: Generated by Spectral Simulation API",
    ]
    msp = "\n".join(header) + "\n" + peaks_block
    return msp, safe_filename(pred["smiles"]) 