version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend/models:/app/models
    ports:
      - "5000:5000"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge 