version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    volumes:
      - model-data:/app/backend/models
    ports:
      - "5051:5000"
    environment:
      - AZURE_STORAGE_CONNECTION_STRING
      - AZURE_STORAGE_CONTAINER
      - AZURE_STORAGE_BLOB
      - LOCAL_MODEL_PATH
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  model-data:
    driver: local 